### ISSUE TITLE
Could you please provide a link of your paper?

### ISSUE THREAD

**Issue by JunzaiYa** [imperial-qore/TranAD#12]
Hello, your code readme.md file mentions your paper: "TranAD: Deep Transformer Networks for Anomaly Detection in Multivariate Time Series Data" was received by VLDB 2022, but I did not find it.Could you please provide a link?

**Comment by shreshthtuli** [comment]
Our paper is available on arxiv: https://arxiv.org/abs/2201.07284.
The paper is in the camera ready stage of the conference and a link shall be added to the readme as soon as it is available.
