### ISSUE TITLE
Hello, some questions about your dataset and algorithm

### ISSUE THREAD

**Issue by SLZWVICTOR** [imperial-qore/TranAD#14]
Hello, I am very interested in your work and I wanna follow it. But some of the datasets are not standard dataset. For example, the SWaT dataset has only 1 dimension, could you please tell me how to preprocess the dataset? The UCR is not available according to the website you given. Besides, when I apply the MAD_GAN method on D_12 dataset of SMAP, it got stuck in a loop in the POT algorithm, could you please tell me how to solve this problem?

**Comment by shreshthtuli** [comment]
Thanks for your interest in our project. To run TranAD on SWaT, please follow the instructions in #3. UCR dataset is available at this link: https://compete.hexagon-ml.com/practice/competition/39/. Please open the 'data' tab and follow the instructions. The current hyperparameter values have been tuned for the default dataset files for ease of use. We shall update the repo for all files soon.

**Comment by SLZWVICTOR** [comment]
Thank you for your reply, however, using the instructions in #3, the f1-score is still 0 on SWaT dataset, could you please tell me the preprocessing method to transform the SWAT dataset into the 1-dimensional data in your code? Besides, the UCR data is still not available because I can not receive the verification code when registering, is there any other way to get the dataset?
