### ISSUE TITLE
POT evaluation

### ISSUE THREAD

**Issue by Ilablo** [imperial-qore/TranAD#15]
Thanks for this interesting work!
I have a question about pot_eval function. Is it possible to use it without the ground truth labels or are they necessary?
Because evaluating the time-series is not always possible to have the labels.

Thanks again

**Comment by shreshthtuli** [comment]
We need labels to evaluate the performance and calculate metrics such as precision, recall, accuracy and F1 scores. This has been directly taken from here https://github.com/NetManAIOps/OmniAnomaly/blob/master/omni_anomaly/eval_methods.py.
