### ISSUE TITLE
Questions on SMD dataset

### ISSUE THREAD

**Issue by ejjun92** [imperial-qore/TranAD#17]
Hello, I was very impressed with your work and would like to reference your work.

In your paper, you said that you used machines 1-1, 2-1, 3-2, and 3-7 of the SMD dataset. So, is the performance of the result table averaged out of each? Or is it all datasets in one place, trained and tested at once?

**Comment by ejjun92** [comment]
Thank you very much for your reply！:)

**Comment by yunchispk** [comment]
> Thanks for your appreciation and interest in our work. We tune the hyperparameters for each file separately. To get the overall score, we sum the true positives, true negatives, false positives and false negatives and evaluate precision, recall and other metrics.

Thank you for your excellent work!
I wonder if you have any principles or basis to follow in the process of adjusting hyperparameters separately?
