### ISSUE TITLE
result depends on random seed

### ISSUE THREAD

**Issue by zeyuyun1** [imperial-qore/TranAD#21]
It seems like the result is very sensitive to random seed. If you set [This line](https://github.com/imperial-qore/TranAD/blob/34c6d532ff3215189a7840f08fb74027b6a108ee/src/models.py#L12) to be `torch.manual_seed(11)` and run TranAD model on UCR dataset. You will actually get 0 f1 score. Seems to be a problem of SPOT. Is this expected?

<img width="677" alt="image" src="https://user-images.githubusercontent.com/43428393/171822232-d622f585-3046-4ed6-846f-013ae74760b0.png">

**Comment by shreshthtuli** [comment]
Please use the `--retrain` option.

**Comment by zeyuyun1** [comment]
I am still getting the same result even with the --retrain option.
<img width="608" alt="Screen Shot 2022-06-04 at 12 02 40 AM" src="https://user-images.githubusercontent.com/43428393/171902982-78d8f9db-43cf-4714-b351-c320cde4ace4.png">

**Comment by shreshthtuli** [comment]
Please ensure the testbed is same as described in the paper, with same pytorch version.
