### ISSUE TITLE
Questions about complete sequence in the paper 

### ISSUE THREAD

**Issue by qihuagao** [imperial-qore/TranAD#22]
Thanks a lot for sharing the great paper and the code.
While I read  "The above operations generate attention weights using the input time-
series windows and the complete sequence to capture temporal
trends within the input sequences"  in the paper, does it mean to use entire time series up to current timestamp?

Also, I didn't manage to find the implementation in the code, could you elaborate complete sequence, and thanks in advance for help.

**Comment by shreshthtuli** [comment]
Yes. Complete series in the abtract model in the paper means the series from timestamp 0 onwards. This can be truncated for data efficiency if not affecting performance. In the code, we use the complete window as the series.
