### ISSUE TITLE
Can not reproduce the experiment results 

### ISSUE THREAD

**Issue by HaoYang-219** [imperial-qore/TranAD#23]
Thanks for releasing the code!
However, when I reproduce the results, such as TranAD method on SMAP dataset,  the result is 
{'FN': 0,
 'FP': 182,
 'Hit@100%': 1.0,
 'Hit@150%': 1.0,
 'NDCG@100%': 1.0,
 'NDCG@150%': 1.0,
 'ROC/AUC': 0.9882686605646513,
 'TN': 7575,
 'TP': 748,
 'f1': 0.8915325929177795,
 'precision': 0.8043010666204187,
 'recall': 0.9999999866310163,
 'threshold': 0.16133320075167037}
the AUC is lower than your paper's result, this phenomena happens in many experiments, I haven't posted them all.

I have followed your experimental settings, and I also tried other torch versions, all the results are different from your results,
so, could you help me whether the result is different from the paper so much?

Hopes for your reply! 
Thanks

**Comment by shreshthtuli** [comment]
Hi. Thanks for your interest in the project. The AUC score you get is only 0.4% different from the ones reported. Such differences are expected in across platforms and testbeds.

**Comment by shreshthtuli** [comment]
We have added params in src/params.json.
