### ISSUE TITLE
Questions on Focus score

### ISSUE THREAD

**Issue by robbyyuu** [imperial-qore/TranAD#26]
Hello,
Thanks for sharing the code.
I have a question about the focus score. According to the paper, the shape of the focus score should be the same as W. How does it concatenate to C?
And why do you use `c = (x1 - src) ** 2`  instead of `c = (x1 - tgt) ** 2` to calculate the focus score in the code?  I guess `src` here refers to the C in the paper and `tgt` refers to the W in the paper.

**Comment by shreshthtuli** [comment]
Hi. Thanks for your interest in our work. `x1` is the reconstruction from the first phase. The focus score is the deviation between the reconstruction and the input window which is `(x1 - src) ** 2`, calculated using broadcasting.  Hope this helps.
