### ISSUE TITLE
Questions about features

### ISSUE THREAD

**Issue by manijehbashar** [imperial-qore/TranAD#28]
Hi,

Thanks for the interesting paper and organized codes.

Could you please let me know if it is possible to run the code for the case of more than 1 feature, for univariate time series?

For example, as you have explained, UCR is a univariate time series with 1 feature.  Do you have any univariate time series with more than 1 feature among your available codes?

Many thanks in advance!

Best regards,
Manijeh

**Comment by shreshthtuli** [comment]
Hi. Thanks for the question. We assume number of features to be same as the number of variables.

**Comment by manijehbashar** [comment]
Hi Shreshth,

Many thanks for your reply and the help. Much appreciated!

Best regards,
Manijeh
