### ISSUE TITLE
Question about MTAD-GAT

### ISSUE THREAD

**Issue by xeroCBW** [imperial-qore/TranAD#29]
In MTAD-GAT paper, there is  1-D Convolution layer before GAT, but I have not see this process in models.

**Comment by xeroCBW** [comment]
Thank you. I also have another question is that,  MTAD-GAT creates graph by link all node to node 0 and  itself, and this is also different with [ML4ITS](https://github.com/ML4ITS/mtad-gat-pytorch/blob/main/mtad_gat.py).

`
self.g = dgl.graph((torch.tensor(list(range(1, feats+1))), torch.tensor([0]*feats)))
self.g = dgl.add_self_loop(self.g)
`

**Comment by shreshthtuli** [comment]
Yes. The original model uses two different attention types, whereas we combine all features together using a global node.

**Comment by xeroCBW** [comment]
> Yes. The original model uses two different attention types, whereas we combine all features together using a global node.

Thanks a lot for your answer. 

Does having all nodes linked to the global node lead to inaccurate attention scores? 

And in the GDN paper, it uses top-k nodes to create a graph to avoid all nodes.

GDN creates a graph in the model of TranAD
```
src_ids = np.repeat(np.array(list(range(feats))), feats)
dst_ids = np.array(list(range(feats))*feats)

self.g = dgl.graph((torch.tensor(src_ids), torch.tensor(dst_ids)))
self.g = dgl.add_self_loop(self.g)
```
