### ISSUE TITLE
How should I reproduce the performance of TranAD on SWaT?

### ISSUE THREAD

**Issue by littlecabbage** [imperial-qore/TranAD#3]
Excellent work!

I am trying to reproduce the performance of TranAD on the SWaT dataset, but I found that the SWaT data in the `data/SWaT` comes from the [Anomaly_Detection_Tuto](https://raw.githubusercontent.com/JulienAu/Anomaly_Detection_Tuto/master/Data/serie2.json). For copyright reasons, maybe the real SWaT data is not allowed to appear in this repo, but I found that the preprocessing code  for SWaT in `preprocess.py` is still for the data of [Anomaly_Detection_Tuto](https://raw.githubusercontent.com/JulienAu/Anomaly_Detection_Tuto/master/Data/serie2.json), and I didn't find a method to preprocess SWaT.
```python

def load_data(dataset:)
  # other code
  elif dataset == 'SWaT':
    dataset_folder = 'data/SWaT'
    file = os.path.join(dataset_folder, 'series.json')
    df_train = pd.read_json(file, lines=True)[['val']][3000:6000]
    df_test  = pd.read_json(file, lines=True)[['val']][7000:12000]
    train, min_a, max_a = normalize2(df_train.values)
    test, _, _ = normalize2(df_test.values, min_a, max_a)
    labels = pd.read_json(file, lines=True)[['noti']][7000:12000] + 0
    for file in ['train', 'test', 'labels']:
	    np.save(os.path.join(folder, f'{file}.npy'), eval(file))
```

How should I reproduce the performance of TranAD on SWaT?

I would appreciate your suggestions,
Cheers

**Comment by shreshthtuli** [comment]
Thanks for your interest in our work. The series.json has been downloaded from the link in readme as `data/SWaT/series.json`. You just need to run `python3 preprocess.py SWaT` and then `python3 main.py --model <model> --dataset SWaT --retrain`.

**Comment by shreshthtuli** [comment]
Hi. This is a refactored code for ease of use. To run using the complete SWaT dataset, you may request for the dataset from the iTrust website (as we do not have the data distribution rights) and save the files in the `data/SWaT/` folder. Then replace the preprocessing function with the following
```python
	elif dataset == 'SWaT':
		dataset_folder = 'data/SWaT/'
		df_train = pd.read_csv(dataset_folder + "SWaT_Dataset_Normal_v1.csv", nrows=1e4)
		df_train = df_train.drop(['Timestamp', 'Normal/Attack'], axis=1)
		df_test = pd.read_csv(dataset_folder + "SWaT_Dataset_Attack_v0.csv", sep=';', nrows=1e4)
		labels = [ float(label!= 'Normal' ) for label  in df_test["Normal/Attack"].values]
		df_test = df_test.drop(['Timestamp', 'Normal/Attack'], axis=1)
		df_train, df_test = transformstr(df_train), transformstr(df_test)
		train, min_a, max_a = normalize3(df_train.values)
		test, _, _ = normalize3(df_test.values, min_a, max_a)
		size = train.shape[0]
		labels = np.broadcast_to(np.array(labels).reshape(-1, 1), test.shape)
		print(train.shape, test.shape, labels.shape)
		for file in ['train', 'test', 'labels']:
			np.save(os.path.join(folder, f'{file}.npy'), eval(file))
```
and change learning rate in `constants.py` to 0.0003.

**Comment by Donek1** [comment]
hello, i have requested for the SWaT dataset, and the dataset is like the following picture.
![image](https://user-images.githubusercontent.com/42731205/170625059-fd0ccb0c-e6ef-446d-be9a-dc6e1e2aa592.png)
I want to ask how to use the code? I didn't see the "SWaT_Dataset_Normal_v1.csv" and the "Normal" folder.

> Hi. This is a refactored code for ease of use. To run using the complete SWaT dataset, you may request for the dataset from the iTrust website (as we do not have the data distribution rights) and save the files in the `data/SWaT/` folder. Then replace the preprocessing function with the following
> 
> ```python
> 	elif dataset == 'SWaT':
> 		dataset_folder = 'data/SWaT/'
> 		df_train = pd.read_csv(dataset_folder + "SWaT_Dataset_Normal_v1.csv")
> 		df_train = df_train.drop(['Timestamp', 'Normal/Attack'], axis=1)
> 		df_test = pd.read_csv(dataset_folder + "SWaT_Dataset_Attack_v0.csv", sep=';')
> 		labels = [ float(label!= 'Normal' ) for label  in df_test["Normal/Attack"].values]
> 		df_test = df_test.drop(['Timestamp', 'Normal/Attack'], axis=1)
> 		df_train, df_test = transformstr(df_train), transformstr(df_test)
> 		train, min_a, max_a = normalize3(df_train.values)
> 		test, _, _ = normalize3(df_test.values, min_a, max_a)
> 		size = train.shape[0]
> 		labels = np.broadcast_to(np.array(labels).reshape(-1, 1), test.shape)
> 		print(train.shape, test.shape, labels.shape)
> 		for file in ['train', 'test', 'labels']:
> 			np.save(os.path.join(folder, f'{file}.npy'), eval(file))
> ```
> 
> Also define a helper function in this file
> 
> ```python
> def transformstr(df):
> 	for i in list(df): 
> 		df[i] = df[i].apply(lambda x: str(x).replace("," , "."))
> 	df = df.astype(float)
> 	return df
> ```
> 
> and change learning rate in `constants.py` to 0.0003 and POT threshold parameter in `lm_d` to 0.95 from 0.993.

**Comment by Donek1** [comment]
> hello, i have requested for the SWaT dataset, and the dataset is like the following picture. ![image](https://user-images.githubusercontent.com/42731205/170625059-fd0ccb0c-e6ef-446d-be9a-dc6e1e2aa592.png) I want to ask how to use the code? I didn't see the "SWaT_Dataset_Normal_v1.csv" and the "Normal" folder.
> 
> > Hi. This is a refactored code for ease of use. To run using the complete SWaT dataset, you may request for the dataset from the iTrust website (as we do not have the data distribution rights) and save the files in the `data/SWaT/` folder. Then replace the preprocessing function with the following
> > ```python
> > 	elif dataset == 'SWaT':
> > 		dataset_folder = 'data/SWaT/'
> > 		df_train = pd.read_csv(dataset_folder + "SWaT_Dataset_Normal_v1.csv")
> > 		df_train = df_train.drop(['Timestamp', 'Normal/Attack'], axis=1)
> > 		df_test = pd.read_csv(dataset_folder + "SWaT_Dataset_Attack_v0.csv", sep=';')
> > 		labels = [ float(label!= 'Normal' ) for label  in df_test["Normal/Attack"].values]
> > 		df_test = df_test.drop(['Timestamp', 'Normal/Attack'], axis=1)
> > 		df_train, df_test = transformstr(df_train), transformstr(df_test)
> > 		train, min_a, max_a = normalize3(df_train.values)
> > 		test, _, _ = normalize3(df_test.values, min_a, max_a)
> > 		size = train.shape[0]
> > 		labels = np.broadcast_to(np.array(labels).reshape(-1, 1), test.shape)
> > 		print(train.shape, test.shape, labels.shape)
> > 		for file in ['train', 'test', 'labels']:
> > 			np.save(os.path.join(folder, f'{file}.npy'), eval(file))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also define a helper function in this file
> > ```python
> > def transformstr(df):
> > 	for i in list(df): 
> > 		df[i] = df[i].apply(lambda x: str(x).replace("," , "."))
> > 	df = df.astype(float)
> > 	return df
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and change learning rate in `constants.py` to 0.0003 and POT threshold parameter in `lm_d` to 0.95 from 0.993.

Helo, i make some mistakes. I have saw the files. It's in the "SWaT.A1 _ A2_Dec 2015" folder, THANK YOU.

**Comment by eventhorizon7** [comment]
我很好奇，您是否在SWaT数据集上重现了性能
