### ISSUE TITLE
Questions about cleaning of MSDS dataset 

### ISSUE THREAD

**Issue by YUJIN-1221** [imperial-qore/TranAD#30]
Hello.
Thanks for sharing the code.

I'm going to use MSDS dataset for my project, so I am referring to your MSDS preprocessing code.
There are some parts that are not understood in the cleaning code of MSDS.

1. 
Why are all elements of  `d` objects recorded as 0 in **'data/MSDS/clean.py'** as below image?

![image](https://user-images.githubusercontent.com/78401311/181055002-2a1a43e1-9c71-4d6c-9053-0635a04bef13.png)

2. 
And what is the difference between **'data/MSDS/labels.csv'** and the **'labels.csv'** made by **'data/MSDS/clean.py'**?
I downloaded MSDS dataset and applied your code. 
The shape of **'train.csv', 'test.csv', and 'labels.csv'** made by **'data/MSDS/clean.py'** were all (146430, 11), but the shape of **'data/MSDS/labels.csv'** were (29286, 11).
How can I use the two different **'labels.csv'**?

Thank you.

**Comment by shreshthtuli** [comment]
Thanks for your interest in the project. Please use the labels.csv provided as part of this repository and run preprocess.py to preprocess files.

**Comment by Labaien96** [comment]
Hi,

Same issue here. I have followed your steps: first I have run clean.py and then I have run preprocess.py. The labels shape I get after preprocessing is (146646,10), and the shape of test.npy is (29330,10). Is there something I forgot? How can I get test.npy and labels.npy with the same shape?

Thanks in advance.
