### ISSUE TITLE
OmniAnomaly Implementation missing guassian state space model

### ISSUE THREAD

**Issue by alexmoore-huma** [imperial-qore/TranAD#31]
https://github.com/imperial-qore/TranAD/blob/f30a13c2fc3010632f1a57d60011c710fb053a52/src/models.py#L126

Hey just to let you know I think you OmniAnomaly implementation is incomplete. The original paper includes a gaussian state space model to capture temporal interactions between latent variables.

Link to the original paper:
https://netman.aiops.org/wp-content/uploads/2019/08/OmniAnomaly_camera-ready.pdf

**Comment by shreshthtuli** [comment]
Hi. Yes, we are aware of this minor detail. The current implementation is for ease of use for someone new to the field.

**Comment by alexmoore-huma** [comment]
Out of interest were the results you reported in your paper for OmniAnomaly obtained using this implementation?

**Comment by shreshthtuli** [comment]
We used the official implementation of the OmniAnomaly method to generate results: https://github.com/NetManAIOps/OmniAnomaly. Interesting to see that our numbers are generally better than the ones reported in the KDD'19 paper.
