### ISSUE TITLE
Thank you for your excellent work

### ISSUE THREAD

**Issue by smartleizi** [imperial-qore/TranAD#32]
Thank you for your excellent work, which is of great help to me！！
I set my own code environment to be the same as yours.
1 When I run the data processing code, I find that there are two data sets (wadi and MSDS) with problems, which are data missing.
python3 preprocess. py SMAP MSL SWaT WADI SMD MSDS UCR MBA NAB

2 When I run the code of the model, the result is better than yours
{'FN': 0,
 'FP': 158,
 'Hit@100%': 1.0,
 'Hit@150%': 1.0,
 'NDCG@100%': 1.0,
 'NDCG@150%': 1.0,
 'ROC/AUC': 0.9898156503803017,
 'TN': 7599,
 'TP': 748,
 'f1': 0.9044690371347901,
 'precision': 0.8256070549049994,
 'recall': 0.9999999866310163,
 'threshold': 0.19522593999128435}

**Comment by shreshthtuli** [comment]
Thanks for your interest in our work. 1. For WADI and MSDS please contact dataset owners to get the data. 2. Could you give more details on which model you are using and on what dataset?

**Comment by smartleizi** [comment]
Thank you for your reply!
1 The models and data I run are as follows:
python main.py --model TranAD --dataset NAB --retrain 

2 I downloaded the other two data and put it in the specified folder according to your method. The data processing was successful.

3 When I run the code, I encounter the following problems.
I tried to solve it, but I did not succeed. I need your help.

python3 main.py --model TranAD --dataset MSDS --retrain

Traceback (most recent call last):
  File "main.py", line 334, in <module>
    result, pred = pot_eval(lt, l, ls); preds.append(pred)
  File "D:\00file2\py_cmdcode\python_test\TranAD\src\pot.py", line 147, in pot_eval
    pred, p_latency = adjust_predicts(score, label, pot_th, calc_latency=True)
  File "D:\00file2\py_cmdcode\python_test\TranAD\src\pot.py", line 45, in adjust_predicts
    raise ValueError("score and label must have the same length")
ValueError: score and label must have the same length

**Comment by smartleizi** [comment]
Yes, I read it.
I first  run clean.py and then preprocess.py，python main.py --model TranAD --dataset MSDS --retrain

**Comment by zzata** [comment]
> Yes, I read it. I first run clean.py and then preprocess.py，python main.py --model TranAD --dataset MSDS --retrain

I have the same problem. Have you solved it? After clean.py and preprocessing.py, the length of label .csv and the length of test.csv are different.

**Comment by Liyicong98** [comment]
I have the same problem.Have you solved it ?
lt: (29286,)
l: (29286,)
ls: (146430,)
How to modify it？

**Comment by shreshthtuli** [comment]
Please truncate to the lowest count.
