### ISSUE TITLE
About the cuda version code.

### ISSUE THREAD

**Issue by eventhorizon7** [imperial-qore/TranAD#34]
Hi, I noticed that you updated some parameters, will you release the cuda version of the code next?

**Comment by shreshthtuli** [comment]
We do not have any immediate plans of developing a GPU friendly version of the code as reproducing results using CPUs is fairly quick. We shall let you know if this is in the works. Thanks.

**Comment by eventhorizon7** [comment]
I also have a question about MSL or SMAP datasets, does each training train each subset of the dataset (e.g. C1, C2) separately, or does it train all the data at once?

**Comment by shreshthtuli** [comment]
We train each file independently.
