### ISSUE TITLE
Where should I make changes if I want to support GPU correctly?

### ISSUE THREAD

**Issue by yunchispk** [imperial-qore/TranAD#37]
Awesome work!
But I found that all models and data sets do not support computing on GPU. They are all done with CPU, which causes time consumption trouble for me to use the complete dataset to train further. I want to know why this project does not use the GPU and where I should make changes if I want to support the GPU correctly. Thank you!

**Comment by shreshthtuli** [comment]
You would need to make changes to send model and datasets to gpu memory. This is not a pressing direction that we are pursuing for this project at the moment.
