### ISSUE TITLE
Question about MSL dataset

### ISSUE THREAD

**Issue by guoguozy** [imperial-qore/TranAD#38]
Hello, thanks for sharing your excellent work!
As your article mentioned,  we consider only the three non-trivial ones (A4, C2 and T1) pointed out by [37]. But I found that the labels of MSL are M-6,M-1,M-2,S-2,P-10,T-4,T-5,F-7,M-3,M-4,M-5,P-15,C-1,C-2,T-12,T-13,F-4,F-5,D-14,T-9,P-14,T-8,P-11,D-15,D-16,M-7,F-8. and could not find the A4, C2 and T1. 
Could you please tell me which one is used in your experiment?

**Comment by shreshthtuli** [comment]
Thanks. Please refer to src/params.json.
