### ISSUE TITLE
reproduce results

### ISSUE THREAD

**Issue by JC0624** [imperial-qore/TranAD#39]
First of all thank you for your excellent work. But I have a doubt, when I run the comparison algorithm in your project, I get results that are inconsistent with your paper and much higher.
<img width="268" alt="Snipaste_2022-09-14_20-08-11" src="https://user-images.githubusercontent.com/64187594/190149629-6a52e8fa-8674-4bbb-8675-9a4618cbe8ea.png">
<img width="208" alt="Snipaste_2022-09-14_20-08-34" src="https://user-images.githubusercontent.com/64187594/190149678-3073f171-714c-4ef8-93a8-df0cbe1072c1.png">

**Comment by shreshthtuli** [comment]
Thanks for your interest in our work. Slight variations in the results are expected. The score you get is within 2% of the reported number, which is not surprising and is possible due to variation in test setup.
