### ISSUE TITLE
Inconsistency in reported numbers

### ISSUE THREAD

**Issue by mistycheney** [imperial-qore/TranAD#4]
Thanks for sharing such clean code. I'm trying it out with the UCR dataset, and have a few questions:
1. In the result table in README, the UCR F1 column is a duplicate of the P column.
2. The results in README are different from those in the arxiv paper. Which one is more accurate?
3. I got much lower F1 number on UCR than reported results for a few baselines such as MAD_GAN (F1=0.7 average of 3 random runs). Do the baselines require dataset-specific hyperparameter tuning, or will the same hyperparameters that generate the reported results be used by default?

**Comment by shreshthtuli** [comment]
Many thanks for your interest in our project. Thanks for pointing out the inconsistencies, we shall resolve these soon. This code has a static set of hyperparameters for the models for ease of use. We are working to finalize the parameters used for generating the results and the grid-search strategy for hyperparameter tuning, which we shall upload as part of a separate branch as soon as it is ready.
