### ISSUE TITLE
Complete sequence

### ISSUE THREAD

**Issue by rashmikaslikar** [imperial-qore/TranAD#40]
Thank you for your excellent work. But I have a doubt regarding the complete sequence. What exactly do you mean by complete sequence (C)? What is the difference between input window (W) and complete sequence (C)? It would really help if you could explain.
Looking forward to your response. Thank you.

**Comment by shreshthtuli** [comment]
Yes. Complete series in the abtract model in the paper means the series from timestamp 0 onwards. This can be truncated for data efficiency if not affecting performance. In the code, we use the complete window as the series.
