### ISSUE TITLE
About SWaT dataset test time is too long, can not produce results, what should I do

### ISSUE THREAD

**Issue by eventhorizon7** [imperial-qore/TranAD#41]

**Comment by eventhorizon7** [comment]
I use
CPU : 14 cores
RAM: 160 GB
GPU: NVIDIA GeForce RTX 3090

but
![image](https://user-images.githubusercontent.com/101782672/190846624-15506b12-b1ca-428d-bab0-b5afdd2908bb.png)

**Comment by shreshthtuli** [comment]
It seems like there is some issue with your system or pytorch installation as 3000+ seconds for training is too high.

**Comment by eventhorizon7** [comment]
When my cpu is R7 5800 one epoch time is 400+ seconds , because I can't use gpu, how should I solve the problem that I can't test on SWaT dataset?

**Comment by eventhorizon7** [comment]
I seem to have found the problem here in pot_eval.
![image](https://user-images.githubusercontent.com/101782672/190992302-ecd6b1fd-3c7b-4837-9635-11fc40f8d599.png)
![image](https://user-images.githubusercontent.com/101782672/190992372-8f22914b-c115-4868-a6b1-3e5ad6b073c1.png)
It keeps looping here, how do I fix it？

**Comment by eventhorizon7** [comment]
lms becomes very large during the loop

**Comment by eventhorizon7** [comment]
I made the mistake of being lms getting smaller and smaller and can't get out in the loop

**Comment by eventhorizon7** [comment]
result, pred = pot_eval(lt, l, ls); preds.append(pred)
I found that in this line, when i is at a certain value, the values of lt and l are all 0, resulting in an infinite loop.

**Comment by eventhorizon7** [comment]
When I remove this part of the code, the result I get is
{'FN': 5178,
 'FP': 253109,
 'Hit@100%': 1.0,
 'Hit@150%': 1.0,
 'NDCG@100%': 1.0,
 'NDCG@150%': 1.0,
 'ROC/AUC': 0.6324510394527012,
 'TN': 142189,
 'TP': 49443,
 'f1': 0.2768548424500904,
 'precision': 0.1634198418730195,
 'recall': 0.9052012960390323,
 'threshold': 0.5505070690110198}

**Comment by JC0624** [comment]
> 当我删除这部分代码时，我得到的结果是 {'FN'： 5178， 'FP'： 253109， 'Hit@100%'： 1.0， 'Hit@150%'： 1.0， 'NDCG@100%'： 1.0， 'NDCG@150%'： 1.0， 'ROC/AUC'： 0.6324510394527012， 'TN'： 142189， 'TP'： 49443， 'f1'： 0.2768548424500904， '精度'： 0.1634198418730195， '召回'： 0.9052012960390323， '阈值'： 0.55050706901110198}

Have you validated the results for the "135" and "138" subsets of the UCR dataset? According to what the author said, I set the relevant parameters, but the result is 0.

**Comment by eventhorizon7** [comment]
> 

Sorry, I did not experiment on this dataset

**Comment by JC0624** [comment]
> 安装似乎存在一些问题，因为 3000+ 秒的训练

Hello, I have encountered a similar problem. How do you solve this problem?

**Comment by LyBjer** [comment]
> 我犯了一个错误，就是 lms 越来越小，无法退出循环

I have the same question. Do you solve this problem? How? Thank you!

**Comment by RoadBegin** [comment]
> I made the mistake of being lms getting smaller and smaller and can't get out in the loop
Hi,did you finally find how to slove this problem?i encounter the same situation.I had tried to set lm_d to 0.95 from 0.993 as the author told in  anthor issus but it didn‘ work.

**Comment by RoadBegin** [comment]
> > 我犯了一个错误，就是 lms 越来越小，无法退出循环
> 
> I have the same question. Do you solve this problem? How? Thank you!

Did you slove it?Could you please help me,Thanks.

**Comment by RoadBegin** [comment]
> I made the mistake of being lms getting smaller and smaller and can't get out in the loop

Hi,did you finally find how to slove this problem?i encounter the same situation.I had tried to set lm_d to 0.95 from 0.993 as the author told in anthor issus but it didn‘ work.

**Comment by yexianyao** [comment]
> I made the mistake of being lms getting smaller and smaller and can't get out in the loop

I have the same problem. Could you solve it？

**Comment by UniqueRoHo** [comment]
> lms becomes very large during the loop

I encounter the same situation, too.Have you solve the problem?

**Comment by shreshthtuli** [comment]
I am unable to replicate this in my system and am under the impression that there is some issue with the python installation.
