### ISSUE TITLE
Results on MSL and SMAP datasets

### ISSUE THREAD

**Issue by eventhorizon7** [imperial-qore/TranAD#42]
I saw that you added new parameters about the subsets of both datasets MSL（C-2, T-4）, SMAP(A-4), and I would like to know the final result of the experiment to train each subset independently and have a separate set of hyperparameters for each subset. The final result is an average of the results of these subsets?

**Comment by JC0624** [comment]
> I saw that you added new parameters about the subsets of both datasets MSL（C-2, T-4）, SMAP(A-4), and I would like to know the final result of the experiment to train each subset independently and have a separate set of hyperparameters for each subset. The final result is an average of the results of these subsets?

I also have this question about the final result. I found that "SMD", "SMAP", "MSL", "UCR", "NAB" in the code only load a single dataset file, whether this can represent the whole dataset performance?

**Comment by shreshthtuli** [comment]
You need to run for each file and aggregate the true positives, false positives, true negatives and false negatives to calculate the final F1 scores.
