### ISSUE TITLE
About the final result

### ISSUE THREAD

**Issue by JC0624** [imperial-qore/TranAD#43]
As you said I experimented on other subsets of UCR dataset and aggregated all test results to take their average, but what puzzles me is the results on "135", "137", "138" are all 0. Have you ever encountered this?

**Comment by shreshthtuli** [comment]
Please use the parameter values mentioned in `src/params.json`?

**Comment by JC0624** [comment]
> 请使用 中提到的参数值。`src/params.json`

Thanks for your reply. According to your reply, I modified the corresponding parameters in the "135" subset of UCR "lm_d": "(0.985, 1)", "lr_d": 0.005, but the result is still 0.
<img width="224" alt="Snipaste_2022-09-19_15-03-37" src="https://user-images.githubusercontent.com/64187594/190965665-669c876f-f08c-47c1-9f10-7edde768590b.png">
<img width="77" alt="Snipaste_2022-09-19_15-04-06" src="https://user-images.githubusercontent.com/64187594/190965678-09f2bdf7-2615-4598-a9d3-6bf12d919086.png">
<img width="169" alt="Snipaste_2022-09-19_15-04-27" src="https://user-images.githubusercontent.com/64187594/190965689-a505b467-92a5-4916-a2d7-48063c5d5fdc.png">
<img width="214" alt="Snipaste_2022-09-19_15-07-16" src="https://user-images.githubusercontent.com/64187594/190965790-d32b63e8-7c3e-4737-a68a-a768afa69d0d.png">

**Comment by shreshthtuli** [comment]
This is the result I get for UCR 137. Please double check your setup and parameter values
<img width="841" alt="image" src="https://user-images.githubusercontent.com/34661516/190966987-7d0de2f3-d356-485e-a30c-46c828f1585c.png">

**Comment by JC0624** [comment]
Sorry, I forgot to mention that the training results can be obtained normally on the "137" subset, but the correct results cannot be obtained on "135" and "138".
