### ISSUE TITLE
C and W, anomaly score calculation and O2, differences bettween code and paper.

### ISSUE THREAD

**Issue by agiannoul** [imperial-qore/TranAD#46]
Basically, I can't understand three things

1) based on the code the anomaly score depends only on O2_hat (instead of both O1 and O2_hat, as in the paper)

2) In the paper you suggest providing C and W.
But in the code, it seems that you provide the W as C, and the last element of W as W (which maybe is fine, but I cant follow the process of thinking).

3) I am not sure where is the calculation of O2 (of phase 1)

In general, great work, thank you!

**Comment by shreshthtuli** [comment]
See #40 for more details.
