### ISSUE TITLE
Baseline implementations (OmniAnomaly, DAGMM, GDN)

### ISSUE THREAD

**Issue by WonmoKoo** [imperial-qore/TranAD#48]
First of all, thank you for sharing your works. There are questions regarding your implementations of the baseline models, e.g., OmniAnomaly, DAGMM and GDN. It seems that your implementations do not match the original paper. For OmniAnomaly, simliar to #31, I cannot find codes for the stochastic variable connection techniques and planer normalization flow. Also, loss function for DAGMM does not include sample energy term and regularization on diagonal entries of covariance matrices. Finally, for GDN, sensor embedding, one of the key components, was not considered. 

I wonder if the performances of baselines you reported in your paper obtained is the results obtained by the implementations in src/model.py? Why are the implementations different?

**Comment by shreshthtuli** [comment]
Please refer to the original implementations to reproduce results. These re-implementations are for ease of use. For more accurate numbers, refer to the links mentioned in our paper: https://arxiv.org/pdf/2201.07284.pdf
