### ISSUE TITLE
About MSDS data

### ISSUE THREAD

**Issue by Smile-zbj** [imperial-qore/TranAD#5]
非常感谢你所做的一切，对于MSDS数据集中的labels.csv我有些问题，希望你能够给予回复，你这里给的lable文件里面全部都是0，我想知道，我这边得到官方数据集之后，如何生成label数据集。

**Comment by shreshthtuli** [comment]
We appreciate your interest in your project. The labels.csv in `data/MSDS/` folder is the correct label set for this dataset. You just need to rename train and test csvs from the zebodo link.

**Comment by Smile-zbj** [comment]
非常感谢你的回复，我这边使用的是zebodo链接下的sequential_data\metrics数据集，通过运行preprocess.py生成训练集和测试集，因为我使用的是你文件中的label.csv作为label，导致实验结果非常的离谱，我这边觉得您这个label是不是有问题？因为不可能全部是正确的标签，如果是正确的标签，那我怎么进行异常检测呢？下面是实验结果图。期待得到您的回复。
![image](https://user-images.githubusercontent.com/66618719/163813340-b314697f-e48d-480d-97f4-8bb68a945c47.png)

**Comment by shreshthtuli** [comment]
Please use the instructions in readme. Save the csv files in "concurrent data/metrics" in "data/MSDS/metrics" and run clean.py to generate "train.csv" and "test.csv".

**Comment by Smile-zbj** [comment]
我这边重新按照你的指示运行了代码，效果依然不是非常的乐观，非常疑惑为什么label.csv里面全部为正常的标签，不应该含有异常标签吗？

**Comment by shreshthtuli** [comment]
See labels at row 15000. They should be 1 for some columns.

**Comment by Smile-zbj** [comment]
我这边是你文件中的label.csv的结果，您看下是不是有问题？能否你这边重新更新下label.csv
![image](https://user-images.githubusercontent.com/66618719/163816314-68d82970-8a73-46c9-9f5b-b5f02f5b3658.png)

**Comment by shreshthtuli** [comment]
Can you check if your file is the same as that in the github repo? Here is the link for the file https://github.com/imperial-qore/TranAD/blob/main/data/MSDS/labels.csv

**Comment by Smile-zbj** [comment]
非常感谢你的回答，我这边问题已经解决了，文件是不相同，没有想到自己会犯如此愚蠢的错误。您这边方便提供下从zebodo提供的数据集中获取label的代码？

**Comment by shreshthtuli** [comment]
The labels file is not publicly available.

**Comment by Smile-zbj** [comment]
好的，非常十分感谢你的解答，非常的感谢！
