### ISSUE TITLE
Clarification request for window and elem when calling model(window, elem)

### ISSUE THREAD

**Issue by patrickfleith** [imperial-qore/TranAD#53]
Thank you for sharing this amazing work.

Would you be able to clarify the following piece of code of `model.py`:

```python
for d, _ in dataloader:
    local_bs = d.shape[0] 
    window = d.permute(1, 0, 2) 
    elem = window[-1, :, :].view(1, local_bs, feats)
    z = model(window, elem)
```

- What is the purpose`d`, `window` and `elem` in relation to the paper `C`,  `O`, and `W` and what are there expected dimensions?
    - `d.shape = torch.Size([batch_size, model.n_window, number_of_variables_in_time_series])`
    - `window.shape = torch.Size([model.n_window, batch_size, number_of_variables_in_time_series])`
    -  `elem.shape = torch.Size([1, batch_size, number_of_variables_in_time_series])`
- In addition, why is there a `local_bs` in training mode whereas `bs` in inference?

**Comment by moamenelgeneral** [comment]
what can i do with this error
  File "C:/Users/EL GENERAL MOAMEN/Desktop/SMAP work/Codes/TranAD-main/main.py", line 338, in <module>
    df = pd.concat([df, result], ignore_index=True)
  File "C:\ProgramData\Anaconda3\envs\dghl_mad\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\dghl_mad\lib\site-packages\pandas\core\reshape\concat.py", line 304, in concat
    sort=sort,
  File "C:\ProgramData\Anaconda3\envs\dghl_mad\lib\site-packages\pandas\core\reshape\concat.py", line 384, in __init__
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'dict'>'; only Series and DataFrame objs are valid

**Comment by shreshthtuli** [comment]
d is the datapoint, window is the input time series window that relates to C, elem is the W input. See #40.
We have two different batch sizes for training and inference.

**Comment by patrickfleith** [comment]
Hi, sorry to brings this up again but I am still confused by this. Maybe a first question:
- What is model.n_window ? I expect it to be the number of timestamp per W_t
- If yes, according to your previous answer, if elem is the W input, it should have one of the dimension of length n_window but it doesn't when I run it. elem has shape (1, bs, number_of_variables_in_time_series)
