### ISSUE TITLE
Questions about datasets

### ISSUE THREAD

**Issue by zhaotianzi** [imperial-qore/TranAD#57]
i have a question about the SWaT and WADI.
I saw their introduction in Table 1, but it is not the same as what I actually got the dimension and quantity
![image](https://user-images.githubusercontent.com/33385974/206115158-77465e3c-1d62-4f4d-86b5-95891924ff58.png)

and i get the dim and number after run preprocesse.py
![image](https://user-images.githubusercontent.com/33385974/206115907-10bbcee7-bfbd-4c66-bf1a-584557983a3b.png)

I did not find the basis for data selection in the paper
![image](https://user-images.githubusercontent.com/33385974/206116319-f7ae8709-7760-4cdd-8359-97cfcb9c41cd.png)

I would like to confirm the dimensions and number actually used in the actual paper

**Comment by shreshthtuli** [comment]
Thanks for your interest in our work. The datasets used for generating the results in the paper are the complete datasets from the respective sources (see references in the paper). The ones used in this repo are placeholders for ease of use.
