### ISSUE TITLE
Or why c = (x1 - src) ** 2 not c = (x1 - tgt) ** 2? i'm confused ~  I think this is not consistent with the Figure 1 in the paper.

### ISSUE THREAD

**Issue by Masquerades2015** [imperial-qore/TranAD#58]
Or  why c = (x1 - src) ** 2 not c = (x1 - tgt) ** 2?   i'm confused  ~

**Comment by zzata** [comment]
Maybe the shape of x1 and the shape of src are both (10, 128, feats), the shape of tgt is (1, 128, feats). I guess src is conplete sequence and tgt means input window in Figure 1

**Comment by patrickfleith** [comment]
Agree with @Masquerades2015 I get x1 of shape (1, batch_size, feats) but src is is (K, batch_size, feats). There seems to be a lot of inconsistencies. It would really help if the authors would specify for each variable in the code what are their dimensions, and to what they correspond in the paper. The more I dig and understand the code, the more it seems to be inconsistent with the paper description (including Figure 1). @shreshthtuli could you help with that one? Are you working on a followup for TranAD? If yes, any more details would be appreciated.

**Comment by patrickfleith** [comment]
We can check #26

**Comment by shreshthtuli** [comment]
The focus score is the deviation between the reconstruction and the input window which is (x1 - src) ** 2, calculated using broadcasting. Hope this helps.
