### ISSUE TITLE
SMAP Dataset preprocessing

### ISSUE THREAD

**Issue by Labaien96** [imperial-qore/TranAD#59]
First of all, thank you for your work. I have some doubts about the SMAP dataset. I have run the preprocessing.py file with the SMAP dataset and the test data is not scaled between 0 and 1 in some dimensions. For example, dimension 0 of file A_1 has data with values up to 50,000 after preprocessing. What is the reason for this?

**Comment by shreshthtuli** [comment]
We use min-max scaling w.r.t the training dataset for fair comparison with prior work. This can cause such discrepancies.
