### ISSUE TITLE
GPU unavailable

### ISSUE THREAD

**Issue by limtyai** [imperial-qore/TranAD#6]
Cannot get the env variable of GPU_STATUS_FILE, no data report to scheduler. This is not an error. It is because the scheduler of the cluster did not enable this feature.

**Comment by shreshthtuli** [comment]
The current code is refactored to work only on CPU to avoid errors. We shall update the code in a separate `gpu` branch with support for CUDA.

**Comment by limtyai** [comment]
Cool~
Thank you very much!
