### ISSUE TITLE
The code of TranAD is not consistent with Figure1

### ISSUE THREAD

**Issue by zzata** [imperial-qore/TranAD#60]

**Comment by zzata** [comment]
Thank you the shared code,  I learned a lot from it. But I have some doubts about the network structure of the code.
When I read the code, I find: 
1. The essence of window Encoder in Figure1 is Window Encoder in [class TranAD], 
2. The Decoder1 and Decoder2 in Figure1 are self.fcn in [class TranAD].
3. There are two value as output in TranAD(x1 and x2)

Here are my main doubts:
1. In [class TranAD], The tgt and memory input Transformerdecoder1 and Transformerdecoder2 and then both input self.fcn to obtain x1 and x2, which means two Window Encoders and one Decoder. **It is a contradiction with Figure 1**. 
2. And the x1 means O1 and the x2 means /hat{O2}, the output of model does not Include O2, which means the O2 participate in the calculation of losses and **it is different from the eq(10) of paper**.

I have gained a lot from your articles and code, thank you again for sharing, and hope you have time to answer my doubts.

**Comment by aatifjiwani** [comment]
+ 1

**Comment by aatifjiwani** [comment]
For me, the main source of confusion is that Figure 1 in the paper labels the separate `Sigmoid(FCN(x))` components as Decoder 1 and Decoder 2 and labels a single Transformer Decoder layer as "Window Encoder". 
However, it seems to be the opposite - there is a single `fcn` / `Sigmoid(FCN(x))` layer and 2 separate Transformer Decoders. While the architecture in the code does make intuitive sense, this discrepancy does make further work a bit confusing.

**Comment by patrickfleith** [comment]
I agree with @aatifjiwani I and I also noticed this discrepency. There are two transformers decoders in the code, and a unique `fcn` / `sigmoid(FCN)`. I am afraid however, it is not the only discrepancy in Figure 1 with respect to the code.

**Comment by shreshthtuli** [comment]
Thanks for your questions. For the results in the paper we need one TransformerDecoder and two FCN decoders. However, we realized two TransformerDecoders and one FCN decoder is slightly more robust in training.
