### ISSUE TITLE
INCORRECT EVALUATION

### ISSUE THREAD

**Issue by mohayl** [imperial-qore/TranAD#61]
all algorithms are evaluated based on POT, which is no the same as the original implementation of each algorithms.
POT is used in Omnianomaly only.

**Comment by patrickfleith** [comment]
What prevents the authors to use a different method in their study for fair comparison of algorithm between each others?

**Comment by mohayl** [comment]
each algorithms are built with different anomaly scoring techniques

**Comment by mohayl** [comment]
fair comparisons is when they evaluate the algorithms as it is implemented in the original paper

**Comment by shreshthtuli** [comment]
Please check the readme:

Note: to reproduce exact results of baselines, use their original codebases (links given in our paper) as the ones implemented in this repository are not the ones used in the paper, which used the original versions. The versions provided here are for use of initial comparison and may not be identical to the original versions.

**Comment by mohayl** [comment]
Ok then, that means the claim of performance improvement is incorrect!?

**Comment by shreshthtuli** [comment]
Performance improvement claims are with respect to the original implementations.
