### ISSUE TITLE
F1 score and accuracy rate are 0, want to know how to solve

### ISSUE THREAD

**Issue by Liyicong98** [imperial-qore/TranAD#66]
The f1 score and accuracy of the results from UCR and MSL datasets are 0.
    f1  precision  recall   TP      TN    FP     FN   ROC/AUC  threshold
0  0.0        0.0     0.0  0.0  5706.0  83.0  111.0  0.492831    0.38542
{'FN': 111,
 'FP': 83,
 'Hit@100%': 1.0,
 'Hit@150%': 1.0,
 'ROC/AUC': 0.4928312316462256,
 'TN': 5706,
 'TP': 0,
 'f1': 0.0,
 'precision': 0.0,
 'recall': 0.0,
 'threshold': 0.3854196283266496}
I need your help.

**Comment by shreshthtuli** [comment]
Please use the hyperparameter values provided in `src/params.json`.
