### ISSUE TITLE
Why the algorithm is only evaluated in some particular files?

### ISSUE THREAD

**Issue by Labaien96** [imperial-qore/TranAD#68]
First of all, thank you for your great work. I'm looking at how you evaluate the models on the different datasets and I have a question. Looking at the main.py file, in the load_dataset function, you only choose some particular datasets, discarding the others. Is there any reason for this?
![image](https://user-images.githubusercontent.com/37838057/219582285-346899b9-2c60-4177-b19e-5dde9cb277da.png)

For example, in UCR datasets if I evaluate TranAD in dataset 137 rather than in 136, I get this results:
![image](https://user-images.githubusercontent.com/37838057/219584846-9e25655d-22cd-4f7d-826f-428e3f0867d6.png)

Am I doing something wrong?

**Comment by shreshthtuli** [comment]
These are just for ease of use. To generate the results in the paper, please use hyperparameters in `src/params.json` for each trace and calculate aggregate results.
