### ISSUE TITLE
Some questions about the performance of the algorithm on the MSL dataset

### ISSUE THREAD

**Issue by zimuges** [imperial-qore/TranAD#69]
Q1:The paper mentions that the MSL dataset uses A4, C2 and T1 subfiles, but according to labeled_anomalies.csv in the project, A4 and T1 belong to the SMAP dataset, and there are no such two files in the MSL generated after preprocessing.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/39946314/219602813-7d833fde-5a8e-4ad1-ab5c-6806983f9a55.png">

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/39946314/219603676-2d31eeeb-7e50-4f67-8aa8-e062efbee9a3.png">
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/39946314/219603739-85a63036-22c9-4054-a278-d0d876cf569a.png">

Q2:And after modifying MSL to load subfile as c2:
<img width="799" alt="image" src="https://user-images.githubusercontent.com/39946314/219604461-6bdc6969-3758-4560-b31a-99261708adb5.png">

The result is as shown in the figure:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/39946314/219604354-fa39850f-90e5-464e-a544-889a3bf1d037.png">

**Comment by alexmoore-huma** [comment]
I believe that these previously closed issues are also relevant here: 

https://github.com/imperial-qore/TranAD/issues/43
https://github.com/imperial-qore/TranAD/issues/33

**Comment by shreshthtuli** [comment]
Please tune hyperparameters using grid search for each trace. You can also use the hyperparameter values provided in src/params.json
