### ISSUE TITLE
Low F1 on the other subsets of SMAP

### ISSUE THREAD

**Issue by Conearth** [imperial-qore/TranAD#8]
Hi Shreshth, when I changed the sub dataset of SMAP from P-1(which you set in the main.py) to others(such as A-1, A-2), the performance becomes very unfavorable. Could you help me out with some explanation of this? Do I need to set different hyperparameters for each subset of SMAP to achieve the the F1 on SMAP which is posted in the paper？
**on SMAP A-1**
{'FN': 0,
 'FP': 8556,
 'Hit@100%': 1.0,
 'Hit@150%': 1.0,
 'NDCG@100%': 0.9999999999999998,
 'NDCG@150%': 0.9999999999999998,
 'ROC/AUC': 0.5,
 'TN': 0,
 'TP': 84,
 **'f1': 0.019257030697754137,**
 'precision': 0.00972222221096965,
 'recall': 0.9999998809523951,
 'threshold': 0.19118465318625302}
**on SMAP A-2**
{'FN': 0,
 'FP': 141,
 'Hit@100%': 1.0,
 'Hit@150%': 1.0,
 'NDCG@100%': 0.9999999999999999,
 'NDCG@150%': 0.9999999999999999,
 'ROC/AUC': 0.9909661711942593,
 'TN': 7663,
 'TP': 110,
 **'f1': 0.6094140115854588,**
 'precision': 0.4382469944921516,
 'recall': 0.9999999090909173,
 'threshold': 0.16136778487480496}

**Comment by shreshthtuli** [comment]
Many thanks for your interest in our project. This code has a static set of hyperparameters for the models for ease of use. We are working to finalize the parameters used for generating the results and the grid-search strategy for hyperparameter tuning for trace-level optimization, which we shall upload as part of a separate branch as soon as it is ready.
