### ISSUE TITLE
How to compute overall metrics for a dataset?

### ISSUE THREAD

**Issue by JinYang88** [imperial-qore/TranAD#9]
Great work for implementing so many baseline models!

For SMD, there are many machines. However, the code only specified one machine (i.e., machine-1-1), and the metric is computed for this machine only.
But the paper reported ONE metric for SMD, how do you aggregate the metrics of all machines to one number? 

Thanks!

**Comment by shreshthtuli** [comment]
Hi. Thanks for your interest in our work. To aggregate the numbers, we add the true positives, false positive, true negatives and false negatives for all files (machines in SMD) and generate precision, recall, F1, etc.

We shall add the tuned hyperparameters for each file for each dataset and the result reproduction scripts soon as a separate branch.
